services:
  # The web service (FastAPI backend)
  - type: web
    name: emotion-detection-api
    runtime: python
    buildCommand: bash build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: emotion-detection-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"

databases:
  # PostgreSQL database
  - name: emotion-detection-db
    plan: free
    ipAllowList: []  # optional, IPs that can connect to this DB 